version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
      - "maven"
    schedule:
      interval: "weekly"
      day: "sunday"
